---
- name: Install email
  apt: name={{item}} state=present
  with_items:
    - offlineimap
    - msmtp
    - mutt

- name: Copy offlineimap and msmtp config
  copy: src={{item}} dest='~/.{{item}}'
  sudo: False
  with_items:
    - offlineimaprc
    - msmtprc
    - muttrc

- name: Copy offlineimap.py
  copy: src=offlineimap.py dest='~/.offlineimap.py'
  sudo: False
