---
- name: Install email
  apt: name={{item}} state=present
  with_items:
    - offlineimap
    - msmtp
    - mutt

- name: Copy offlineimap and msmtp config
  copy: src={{item}} dest='~/.{{item}}'
  sudo: False
  with_items:
    - offlineimaprc
    - offlineimap.py
    - msmtprc
    - muttrc
    - signature

- name: Create mutt directory
  file: path='~/.mutt' state=directory
  sudo: False

- name: Create cache directory
  file: path='~/.mutt/headers' state=directory
  sudo: False

- name: Cron offlineimap
  cron: name='offlineimap' minute='*/5' hour='7-20' job='offlineimap -u quiet -q'
  sudo: False

- name: Cron offlineimap full sync
  cron: name='offlineimap nightly' minute='0' hour='23' job='offlineimap -u quiet'
  sudo: False
