---
- name: Install Sup dependencies
  apt: name={{item}} state=present
  with_items:
    - uuid-dev
    - libncursesw5-dev
    - offlineimap
    - msmtp

- name: Install Sup
  gem: name={{item}} state=latest user_install=no
  with_items:
    - xapian-ruby
    - gpgme
    - sup

- name: Copy sup hooks
  copy: src=hooks dest='~/.sup'
  sudo: False
