---
- name: Install Sup dependencies
  apt: name={{item}} state=present
  with_items:
    - uuid-dev
    - libncursesw5-dev
    - offlineimap
    - msmtp

- name: Install stuff from backports
  apt: name={{ item }} state=present default_release={{ansible_distribution_release}}-backports
  with_items:
    - tree
    - pass
    - gnupg2

- name: Install Sup
  gem: name={{item}} state=latest user_install=no
  with_items:
    - xapian-ruby
    - gpgme
    - sup

- name: Copy offlineimap config
  copy: src=offlineimaprc dest='~/.offlineimaprc'
  sudo: False

- name: Copy offlineimap.py
  copy: src=offlineimap.py dest='~/.offlineimap.py'
  sudo: False

- name: Copy sup hooks
  copy: src=hooks dest='~/.sup'
  sudo: False
