---
- name: Install email
  apt: name={{item}} state=present
  sudo: True
  with_items:
    - offlineimap
    - msmtp
    - mutt

- name: Copy offlineimap and msmtp config
  copy: src={{item}} dest='~/.{{item}}'
  with_items:
    - offlineimaprc
    - offlineimap.py
    - msmtprc
    - muttrc
    - signature

- locale_gen: name=de_CH.UTF-8
  sudo: True

- locale_gen: name=en_US.UTF-8
  sudo: True

- name: Create mutt directory
  file: path='~/.mutt' state=directory

- name: Create empty aliases file
  command: touch ~/.mutt/aliases creates=~/.mutt/aliases

- name: Cron offlineimap
  cron: name='offlineimap' minute='*/5' hour='7-20' job='offlineimap -u quiet -q'

- name: Cron offlineimap full sync
  cron: name='offlineimap nightly' minute='0' hour='23' job='offlineimap -u quiet'
