alias ls='ls --color=auto'
alias ll='ls -alF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ..='cd ..'
alias ...='cd ../..'

alias radio='(cvlc http://live.eliberadio.ro:8002 &)'
alias mergerequest='GITLAB_TOKEN=$(pass puzzle/gitlab_token) bundle exec rake mergerequest'

alias g='git'
__git_complete g _git

alias gs='git status'
__git_complete gs _git_status

alias gc='git commit -m'
__git_complete gc _git_commit

alias gco='git checkout'
__git_complete gco _git_checkout

alias ga='git add'
__git_complete ga _git_add

alias gp='git pull'
__git_complete gp _git_pull

alias gd='git diff'
__git_complete gd _git_diff

alias gb='git branch'
__git_complete gb _git_branch

alias vim='NVIM_LISTEN_ADDRESS=/tmp/nvim.sock vim'

alias gibb="sshfs lorenz.bischof@sftp.iet-gibb.ch: $HOME/gibb/ -o reconnect"

alias t="task"
complete -F _task t

vol() {
    if [ $1 ]; then
        amixer set Master -Mq $1
    fi
    amixer get Master -M | sed -n "$ p" | awk '{print $4}' | sed "s/[^0-9]//g" | awk '{print $1"%"}'
}

vid() {
    xrandr --output HDMI2 --off
    killall -SIGUSR1 redshift
    mpv $@
    xrandr --output HDMI2 --auto --right-of VGA1
    killall -SIGUSR1 redshift
}
