---
- name: Setup Digitalocean Server
  hosts: digitalocean
  sudo: yes
  remote_user: root

  roles:
    - common
    - hhvm
    - role: jdauphant.nginx
      nginx_sites:
        ahornblume:
          - |
            server_name ahornblume.ch;
            listen 80;
            root "{{ doc_root }}{{ item }}";
            index index.php index.html index.htm;
            try_files $uri $uri/ $uri.php?$args;
            location ~ \.(hh|php)$ {
                try_files     $uri =404;
                fastcgi_pass  127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include       fastcgi_params;
            }

  tasks:
    - name: Deploy Code from Bitbucket
      git: repo=git@bitbucket.org:lorenzbi/{{ item }}.git
           dest={{ doc_root }}{{ item }}
           accept_hostkey=yes
      with_items:
        - ahornblume
      when: ansible_hostname == "production"