---
- name: Setup Digitalocean Server
  hosts: digitalocean
  remote_user: root

  roles:
    - common
    - hhvm
    - pcextreme.mariadb
    - respondcms
    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile off
      nginx_sites:
        ahornblume:
          - |
            server_name ahornblume.ch ahornblume.vagrant.dev;
            try_files $uri $uri/ $uri.php?$args;
            {{ include_nginx_hhvm }}
        maplesplendor:
          - |
            server_name maplesplendor.ca maplesplendor.vagrant.dev;
            root /var/www/vhosts/maplesplendor/sites/maplesplendor;
            try_files $uri $uri/ $uri.html;
            {{ include_nginx_hhvm }}
        respond:
          - |
            server_name app.maplesplendor.ca app.maplesplendor.vagrant.dev;
            root "/var/www/vhosts/maplesplendor/";
            location /api/ { try_files $uri $uri/ $uri.php /api/dispatch.php$args; }
            location / { try_files $uri $uri/ /index.html; }
            {{ include_nginx_hhvm }}
