---
- name: Setup Digitalocean Server
  hosts: digitalocean
  remote_user: root

  roles:
    - common
    - hhvm
    - pcextreme.mariadb
    - respondcms
    - role: jdauphant.nginx
      nginx_sites:
        ahornblume:
          - |
            server_name ahornblume.ch ahornblume.vagrant.dev;
            try_files $uri $uri/ $uri.php?$args;
            {{ include_nginx_hhvm }}
        maplesplendor:
          - |
            server_name maplesplendor.ca maplesplendor.vagrant.dev app.maplesplendor.vagrant.dev;
            try_files $uri $uri/ index.php?$args;
            location /api/ { try_files $uri $uri/ $uri.php /api/dispatch.php$args; }
            {{ include_nginx_hhvm }}

  tasks:
    - name: Deploy Code from Bitbucket
      git: repo=git@bitbucket.org:lorenzbi/{{ item }}.git
           dest={{ doc_root }}{{ item }}
           accept_hostkey=yes
      with_items:
        - ahornblume
        - maplesplendor
      when: ansible_hostname == "production"