---
- name: Setup Digitalocean Server
  hosts: digitalocean
  sudo: yes
  remote_user: root

  roles:
    - common
    - hhvm
    - pcextreme.mariadb
    - respondcms
    - role: jdauphant.nginx
      nginx_sites:
        ahornblume:
          - |
            server_name ahornblume.ch;
            try_files $uri $uri/ $uri.php?$args;
            {{ include_nginx_hhvm }}
        maplesplendor:
          - |
            server_name maplesplendor.ca
            try_files $uri $uri/ index.php?$args;
            {{ include_nginx_hhvm }}

  tasks:
    - name: Deploy Code from Bitbucket
      git: repo=git@bitbucket.org:lorenzbi/{{ item }}.git
           dest={{ doc_root }}{{ item }}
           accept_hostkey=yes
      with_items:
        - ahornblume
      when: ansible_hostname == "production"