---
- name: Setup home pc
  hosts: localhost

  vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "Sudo password"
    private: yes

  roles:
    - common
    - dotfiles
    - rvm_io.rvm1-ruby
    - nvm

