---
- name: Setup Raspberry Pi
  hosts: pi
  sudo: yes
  remote_user: pi

  roles:
    - common
    - jnv.debian-backports
    - raspberrypi
    - mailclient
    - role: openvpn
      clients:
        - client

