---
- name: Setup Raspberry Pi
  hosts: pi
  remote_user: root
  gather_facts: no
  pre_tasks:
      - name: Check python
        action: ping
        register: python_installed
        no_log: yes
        ignore_errors: yes

      - name: Install python
        raw: apt-get update && apt-get -y install python
        when: python_installed|failed

      - action: setup
  roles:
      - bobbyrenwick.pip
      - pi
      # - mailclient
