---
- name: Setup work laptop
  hosts: localhost

  vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "Sudo password"
    private: yes

  roles:
    - common
    - dotfiles
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
    - pgilad.nvm

