---

- name: Copy gpg-with-sec script
  copy: src=gpg-with-sec.sh dest=/usr/local/bin/gpg-with-sec mode=0755
  become: yes

- name: Create gnupg directory
  file: path=~/.gnupg state=directory mode=0700

- name: Copy configuration files
  copy: src=gnupg/{{item}} dest=~/.gnupg/{{item}} mode=0600
  with_items:
    - gpg.conf
    - gpg-agent.conf
    - scdaemon.conf

- name: Copy udev rules
  copy: src=40-nitrokey.rules dest=/etc/udev/rules.d
  become: yes

- name: Install gpg software
  pacman: name={{item}} state=present
  become: yes
  with_items:
    - pcsclite
    - libusb-compat

- name: Start pcscd service
  service: name=pcscd state=started enabled=yes
  become: yes
