---

- name: Copy gpg-with-sec script
  copy: src=gpg-with-sec.sh dest=/usr/local/bin/gpg-with-sec mode=0755
  sudo: yes

- name: Disable Gnome-keyring
  file: path={{item}} state=absent
  sudo: yes
  with_items:
    - /etc/xdg/autostart/gnome-keyring-gpg.desktop
    - /etc/xdg/autostart/gnome-keyring-gpg-pantheon.desktop

- name: Install gpg software
  apt: name={{item}} state=installed
  sudo: yes
  with_items:
    - libccid
    - gpgsm
