---

- name: Install i3
  pacman: name={{ item }} state=present
  become: yes
  with_items:
    - i3-wm
    - i3lock
    - i3status
    - dmenu
    - dunst
    - libnotify
    - compton
    - feh
    - redshift
    - xorg-server
    - xorg-server-utils
    - xorg-xinit
    - xf86-video-intel
    - mesa-libgl

- name: Copy i3 config
  copy: src=i3 dest=~/.config

- name: Copy i3status config
  copy: src=i3status dest=~/.config

- name: Enable autologin
  copy: src=getty@tty1.service.d dest=/etc/systemd/system
  become: yes

- name: Copy wallpapers
  copy: src=wallpapers dest=~/.config

- name: Copy xorg config
  copy: src=xorg.conf.d dest=/etc/X11
  become: yes
