---

- name: Install TLP and touchpad driver
  pacman: name={{ item }} state=present
  with_items:
    - xf86-input-synaptics
    - tlp

- name: Start tlp service
  service: name=tlp state=started enabled=yes
  become: yes

- name: Copy monitor hotplug script
  copy: src=monitor-hotplug.sh dest=/usr/local/bin
  become: yes

- name: Copy delayed hibernation service file
  copy: src=suspend-to-hibernate.service dest=/etc/systemd/system
  become: yes
