---

- name: Install latex
  apt: name={{ item }} state=installed
  become: yes
  with_items:
    - latexmk
    - texlive
    - texlive-latex-extra
    - texlive-lang-german

- name: Deploy latex config
  copy: src=latexmkrc dest=~/.latexmkrc
