---

- name: Install apps
  pacman: name={{ item }} state=present
  become: yes
  with_items:
    - bash-completion
    - git                   # commit everything
    - pass
    - transmission-gtk
    - vlc
    - xclip                 # cli clipboard management
    - xdotool               # so vimtex knows if the pdf viewer is already open
    - zathura
    - zathura-pdf-mupdf
    - ruby
    - python-pip
    - task
    - openssh
    - chromium

- name: Copy mirrorlist
  copy: src=mirrorlist dest=/etc/pacman.d
  become: yes

- name: Start dhcpcd service
  service: name=dhcpcd state=started enabled=yes
  become: yes

- include: nvim.yml
- include: latex.yml
- include: tmux.yml
- include: terminal.yml
- include: gpg.yml
- include: jabber.yml
- include: mutt.yml
- include: i3.yml
- include: fonts.yml
