---

- name: Copy mirrorlist
  copy: src=mirrorlist dest=/etc/pacman.d
  become: yes

- name: Install apps
  pacman: name={{ item }} state=present update_cache=yes
  become: yes
  with_items:
    - bash-completion
    - pass
    - transmission-gtk
    - vlc
    - xclip                 # cli clipboard management
    - xdotool               # so vimtex knows if the pdf viewer is already open
    - zathura
    - zathura-pdf-mupdf
    - ruby
    - python-pip
    - task
    - openssh
    - chromium
    - xf86-input-synaptics
    - tlp
    - pkgfile
    - sshfs
    - scrot

- name: Start dhcpcd service
  service: name=dhcpcd state=started enabled=yes
  become: yes

- name: Start tlp service
  service: name={{ item }} state=started enabled=yes
  become: yes
  with_items:
    - tlp
    - tlp-sleep

- include: nvim.yml
- include: latex.yml
- include: terminal.yml
- include: gpg.yml
- include: jabber.yml
- include: mutt.yml
- include: gui.yml
- include: vagrant.yml
- include: fonts.yml
- include: git.yml
- include: laptop.yml
  when: ansible_product_name == "Latitude E7250"
