---

- name: Install apps
  pacman: name={{ item }} state=present
  become: yes
  with_items:
    - bash-completion
    - git                   # commit everything
    - pass
    - transmission-gtk
    - vlc
    - xclip                 # cli clipboard management
    - xdotool               # so vimtex knows if the pdf viewer is already open
    - zathura
    - zathura-pdf-mupdf
    - ruby
    - python-pip

- name: Install apps from aur
  packer: name={{ item }} state=present
  become: yes
  with_items:
    - dtrx

- name: Copy mirrorlist
  copy: src=mirrorlist dest=/etc/pacman.d
  become: yes

- include: nvim.yml
- include: latex.yml
#- include: tmux.yml
- include: terminal.yml
#- include: todo.yml
- include: gpg.yml
#- include: gsettings.yml
#- include: lock.yml
- include: jabber.yml
- include: mutt.yml
- include: i3.yml
- include: fonts.yml
