---

- name: Install mutt
  apt: name=mutt state=installed
  become: yes

- name: Copy mutt directory
  copy: src=mutt/ dest=~/.mutt/

- name: Copy mutt aliases
  copy: content={{ mutt_aliases }} dest=~/.mutt/aliases
