---

- name: Run timedatectl status
  command: /usr/bin/timedatectl status
  changed_when: False
  always_run: yes
  register: timedatectl_result

- name: Copy timesyncd config
  copy: src=timesyncd.conf dest=/etc/systemd/timesyncd.conf
  become: yes

- name: Set timezone
  command: /usr/bin/timedatectl set-timezone Europe/Zurich
  when: "'Europe/Zurich' not in timedatectl_result.stdout"
  become: yes

- name: Enable ntp
  command: /usr/bin/timedatectl set-ntp true
  when: "'Network time on: no' in timedatectl_result.stdout"
  become: yes

- name: Start libvirtd
  service: name=systemd-timesyncd state=started enabled=yes
  become: yes
