---

- name: Add neovim repository
  apt_repository: repo=ppa:neovim-ppa/unstable
  become: yes

- name: Install neovim
  apt: name=neovim state=installed
  become: yes

- name: Install vim
  apt: name=vim state=installed
  become: yes

- name: Install neovim python dependencies
  apt: name={{ item }} state=installed
  become: yes
  with_items:
    - python3-unidecode
    - python3-pip
    - python3-dev

- name: Install neovim python packages
  pip: name=neovim executable=pip3
  become: yes

- name: Set neovim as default vim
  alternatives: name=vim path=/usr/bin/nvim
  become: yes

- name: Deploy neovim config files
  copy: src=nvim dest=~/.config

- name: Install neovim-remote script
  get_url: url=https://raw.githubusercontent.com/mhinz/neovim-remote/master/nvr dest=/usr/local/bin/ mode=0775
  become: yes
