---

- name: Install neovim
  pacman: name=neovim state=present
  become: yes

- name: Install neovim python dependencies
  pacman: name={{ item }} state=present
  become: yes
  with_items:
    - python-unidecode
    - python-pip

- name: Install neovim python packages
  pip: name=neovim
  become: yes

- name: Set neovim as default vim
  file: src=/usr/bin/nvim dest=/usr/bin/vim state=link
  become: yes

- name: Deploy neovim config files
  copy: src=nvim dest=~/.config

#- name: Install neovim-remote script
#  get_url: url=https://raw.githubusercontent.com/mhinz/neovim-remote/master/nvr dest=/usr/local/bin/ mode=0775
#  become: yes
