---

- name: Install terminal
  pacman: name=rxvt-unicode
  become: yes

- name: Install terminal font
  pacman: name=ttf-dejavu
  become: yes

- name: Copy Xresources
  copy: src=Xresources dest=~/.Xresources
  notify: reload rxvt

- name: Copy dircolors
  copy: src=dircolors.256dark dest=~/.dircolors.256dark

- name: Copy bash files
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - bashrc
    - bash_aliases
    - bash_profile
    - xinitrc
    - gitconfig

- name: Disable pc speaker beep
  copy: src=nobeep.conf dest=/etc/modprobe.d
  become: yes
