---

- name: Add user to audio group
  user: name={{ ansible_user_id }} groups=audio append=yes
  become: yes

- name: Install radio dependencies
  package: name={{ item }}
  become: yes
  with_items:
    - vlc
    - lsof
    - alsa-utils

- name: Copy radio script
  copy: src=radio.sh dest=/usr/local/bin/radio mode=755
  become: yes

- name: Disable pc speaker beep
  copy: content='blacklist pcspkr' dest=/etc/modprobe.d/nobeep.conf
  become: yes
