---

- name: Install docker
  package: name={{ item }} state=present
  become: yes
  with_items:
    - docker
    - docker-compose
    - python2-docker

- name: Start docker
  service: name=docker state=started enabled=yes
  become: yes
