---


- name: Install GPG packages
  package: name={{ item }}
  become: yes
  with_items:
    - gnupg2-scdaemon
    - pinentry-gtk

- name: Create gnupg directory
  file: path=~/.gnupg state=directory mode=0700

- name: Copy configuration files
  copy: src=gnupg/{{item}} dest=~/.gnupg/{{item}} mode=0600
  with_items:
    - gpg.conf
    - gpg-agent.conf

- name: Copy nitrokey udev rules
  copy: src=udev/rules.d/40-nitrokey.rules dest=/etc/udev/rules.d/
  become: yes

- name: Install libusb-compat
  package: name=libusb-compat state=present
  become: yes
