---

- name: Create gnupg directory
  file: path=~/.gnupg state=directory mode=0700

- name: Copy configuration files
  copy: src=gnupg/{{item}} dest=~/.gnupg/{{item}} mode=0600
  with_items:
    - gpg.conf
    - gpg-agent.conf

- name: Copy udev rules
  copy: src=40-nitrokey.rules dest=/etc/udev/rules.d
  become: yes

- name: Install libusb-compat
  package: name=libusb-compat state=present
  become: yes
