---

- name: Create gnupg directory
  file: path=~/.gnupg state=directory mode=0700

- name: Copy configuration files
  copy: src=gnupg/{{item}} dest=~/.gnupg/{{item}} mode=0600
  with_items:
    - gpg.conf
    - gpg-agent.conf

- name: Copy nitrokey udev rules
  copy: src=udev/rules.d/40-nitrokey.rules dest=/etc/udev/rules.d/
  become: yes

- name: Install libusb-compat
  package: name=libusb-compat state=present
  become: yes

- name: Download public key
  gpg_import: key_id=34C7D8DEF3CA1548652B393F2285067DAFBA32A6

- name: Download passwords
  git: repo=lorenzbi@bitbucket.org:lorenzbi/pass.git dest=~/.password-store update=no accept_hostkey=yes
  ignore_errors: yes
