---

- name: Install i3
  package: name={{ item }} state=present
  become: yes
  with_items:
    - i3-wm
    - i3lock
    - i3status
    - dmenu
    - dunst
    - libnotify
    - compton
    - feh
    - redshift
    - xorg-server
    - xorg-xinit
    - xorg-xrandr

- name: Copy xinitrc
  copy: content="exec i3" dest=~/.xinitrc

- name: Copy i3 config
  copy: src=i3 dest=~/.config

- name: Copy i3status config
  copy: src=i3status dest=~/.config

- name: Copy i3_focus script
  copy: src=i3_focus.sh dest=/usr/local/bin mode=0755
  become: yes

- name: Enable autologin
  copy: src=getty@tty1.service.d dest=/etc/systemd/system
  become: yes

- name: Copy wallpapers
  copy: src=wallpapers dest=~/.config

- name: Copy dunst config
  copy: src=dunst dest=~/.config

- name: Copy compton config
  copy: src=compton.conf dest=~/.config/compton.conf

- name: Copy xorg config
  copy: src=xorg.conf.d dest=/etc/X11
  become: yes

- name: Copy gtk config
  copy: src=gtk/{{ item }} dest=/etc/
  become: yes
  with_items:
    - gtk-2.0
    - gtk-3.0

- name: Create hushlogin file
  copy: content="" dest=~/.hushlogin
