---

- name: Install TLP and touchpad driver
  package: name={{ item }} state=present
  become: yes
  with_items:
    - xf86-input-libinput
    - tlp

- name: Start tlp service
  service: name=tlp state=started enabled=yes
  become: yes

- name: Install light
  package: name=light
  become: yes

- name: Creates light config directory
  file: path=/etc/light/mincap state=directory
  become: yes

- name: Set min brightness
  copy: content="1" dest=/etc/light/mincap/intel_backlight
  become: yes

- name: Setup sound
  copy: src=asound.conf dest=/etc/asound.conf
  become: yes
