---

- name: Install latex
  package: name={{ item }} state=present
  become: yes
  with_items:
    - texlive-most
    - texlive-bin
    - texlive-langextra
    - pygmentize

- name: Deploy latex config
  copy: src=latexmkrc dest=~/.latexmkrc

- name: Deploy chktexrc
  copy: src=chktexrc dest=~/.chktexrc
