---

- name: Copy mirrorlist
  copy: src=mirrorlist dest=/etc/pacman.d
  become: yes

- name: Install apps
  package: name={{ item }} state=present update_cache=yes
  become: yes
  with_items:
    - pass
    - transmission-gtk
    - xclip                 # cli clipboard management
    - xdotool               # so vimtex knows if the pdf viewer is already open
    - zathura
    - zathura-pdf-mupdf
    - ruby
    - python-pip
    - task
    - openssh
    - chromium
    - pkgfile
    - maim                  # screenshot tool
    - slop                  # allow selection in maim
    - openvpn
    - jdk8-openjdk
    - java-openjfx
    - eclipse-java


- name: Start ifplugd service
  service: name=netctl-ifplugd@{{item}} state=started enabled=yes
  become: yes
  when: item | match('^en')
  with_items: "{{ansible_interfaces}}"

- include: nvim.yml
- include: latex.yml
- include: terminal.yml
- include: gpg.yml
- include: jabber.yml
- include: mutt.yml
- include: gui.yml
- include: vm.yml
- include: fonts.yml
- include: git.yml
- include: ntp.yml
- include: laptop.yml
  when: ansible_product_name == "Latitude E7250"
