---

- name: Copy mirrorlist
  copy: src=mirrorlist dest=/etc/pacman.d
  become: yes

- name: Install apps
  package: name={{ item }} state=present update_cache=yes
  become: yes
  with_items:
    - pass
    - transmission-gtk
    - xclip                 # cli clipboard management
    - xdotool               # so vimtex knows if the pdf viewer is already open
    - zathura
    - zathura-pdf-mupdf
    - ruby
    - openssh
    - chromium
    - pkgfile
    - maim                  # screenshot tool
    - slop                  # allow selection in maim
    - ruby-bundler

- name: Install aur packages
  aur: name={{ item }}
  with_items:
    - pacaur
    - dtrx
    - puppet-lint
    - python-proselint
    - xcape

- name: Copy mimeapps.list
  copy: src=mimeapps.list dest=~/.config/mimeapps.list

- include: network.yml
- include: nvim.yml
- include: latex.yml
- include: terminal.yml
- include: gpg.yml
- include: jabber.yml
- include: mutt.yml
- include: gui.yml
- include: vm.yml
- include: git.yml
- include: timedate.yml
- include: school.yml
- include: autofs.yml
- include: openvpn.yml
- include: cups.yml

- include: laptop.yml
  when: ansible_product_name == "Latitude E7250"

- include: nfs.yml
  when: ansible_product_name != "Latitude E7250"
