---

- name: Install mutt
  package: name=mutt state=present
  become: yes

- name: Copy mutt directory
  copy: src=mutt/ dest=~/.mutt/

- name: Get aliases if possible
  command: pass puzzle/aliases creates=~/.mutt/aliases
  ignore_errors: yes
  register: aliases

- name: Create aliases file
  copy: content={{ aliases.stdout }} dest=~/.mutt/aliases
  when: aliases.changed
