---

- name: Install NFS
  package: name=nfs-utils state=present
  become: yes

- name: Create directories
  file: path={{ item }} state=directory
  become: yes
  with_items:
    - /data
    - /data/old
    - /data/new

- name: Mount disks
  mount: name={{ item.name }} src={{ item.src }} fstype=ext4 state=mounted
  become: yes
  with_items:
    - { name: '/data/old', src: 'UUID=03997049-0de8-4f96-87f8-d655c90f7824' }
    - { name: '/data/new', src: 'UUID=e483ef7a-27d3-4e80-b5aa-d26702ff6e12' }

- name: Export directories
  copy: content="/data/old 192.168.0.0/24(rw,all_squash,insecure)\n/data/new 192.168.0.0/24(rw,all_squash,insecure)" dest=/etc/exports
  register: nfs_exports
  become: yes

- name: Restart NFS immediately if exports are updated.
  service: name=nfs-server state=restarted
  when: nfs_exports.changed

- name: Start NFS service
  service: name={{ item }} state=started enabled=yes
  become: yes
  with_items:
    - statd
    - rpcbind
    - nfs-server
