---

- name: Install neovim
  package: name={{ item }} state=present
  become: yes
  with_items:
    - neovim
    - python-neovim
    - python-unidecode

- name: Install neovim remote
  aur: name=neovim-remote

- name: Set neovim as default vim
  file: src=/usr/bin/nvim dest=/usr/bin/vim state=link
  become: yes

- name: Deploy neovim config files
  copy: src=nvim dest=~/.config
  register: nvim_config

- name: Run PlugInstall
  shell: vim +PlugInstall +qall
  when: nvim_config.changed
