---

- name: Install openvpn
  package: name=openvpn state=present
  become: yes

  # this is needed so ansible sees the files in next task
- name: Allow directory read access
  file: path=/etc/openvpn/client mode=755
  become: yes

- name: Get openvpn config
  command: pass puzzle/vpn/{{item}}-config creates=/etc/openvpn/client/{{item}}.conf
  ignore_errors: yes
  register: openvpnconfig
  with_items:
    - be3
    - rz
    - sys-rz

- name: Install openvpn config
  copy: content="{{ item.stdout }}\n" dest=/etc/openvpn/client/{{item.item}}.conf owner=root mode=600
  when: item.changed and not item.failed|default(false)
  no_log: yes
  become: yes
  with_items: "{{openvpnconfig.results}}"

- name: Install vpn script
  copy: src=vpn.sh dest=/usr/local/bin/vpn mode=755
  become: yes
