---

- name: Install openvpn
  package: name=openvpn state=present
  become: yes

- name: Create openvpn directory
  file: path={{item}} state=directory mode=700
  become: yes
  with_items:
    - /etc/openvpn
    - /etc/openvpn/client

- name: Check openvpn config
  shell: ls -A1 /etc/openvpn/client
  changed_when: False
  register: openvpn_ls
  become: yes

- name: Get openvpn config
  command: pass puzzle/vpn/{{item}}-config
  when: item not in openvpn_ls.stdout
  register: openvpn_config
  ignore_errors: yes
  with_items:
    - be3
    - rz
    - sys-rz

- name: Install openvpn config
  copy: content="{{ item.stdout }}\n" dest=/etc/openvpn/client/{{item.item}}.conf owner=root mode=600
  when: item.changed and not item.failed|default(false)
  no_log: yes
  become: yes
  with_items: "{{openvpn_config.results}}"

- name: Install vpn script
  copy: src=vpn.sh dest=/usr/local/bin/vpn mode=755
  become: yes
