---

- name: Install zsh
  package: name=zsh
  become: yes

- name: Install terminal
  package: name=rxvt-unicode
  become: yes

- name: Change shell to zsh
  user: name={{ ansible_user_id }} shell=/bin/zsh
  become: yes

- name: Copy zsh files
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - zprofile
    - zshrc

#- name: Install terminal fonts
#  package: name={{ item }}
#  become: yes
#  with_items:
#    - ttf-dejavu
#    - ttf-liberation        # fix fonts in chromium pdf viewer

- name: Copy base16-shell
  copy: src=base16-shell dest=~/.config

- name: Copy bash files
  copy: src=Xresources dest=~/.Xresources

- name: Copy radio script
  copy: src=radio.sh dest=/usr/local/bin/radio
  become: yes
