---

- name: Install terminal
  package: name=termite
  become: yes

- name: Copy termite config
  copy: src=termite dest=~/.config

- name: Change shell to zsh
  user: name={{ ansible_user_id }} shell=/bin/zsh
  become: yes

- name: Copy zsh files
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - zprofile
    - zshrc

- name: Disable pc speaker beep
  copy: content='blacklist pcspkr' dest=/etc/modprobe.d/nobeep.conf
  become: yes
