---

# BUG: github.com/pradels/vagrant-libvirt/issues/541
# SOLUTION: wiki.archlinux.org/index.php/Vagrant#vagrant-libvirt

# BUG: github.com/fog/fog-libvirt/issues/16
# SOLUTION: vagrant plugin install fog-libvirt --plugin-version 0.0.3

- name: Install Vagrant
  package: name=vagrant state=present
  become: yes

# Install virtualbox after the modules package, because of multiple providers
#- name: Install Virtualbox
#  package: name={{ item }} state=present
#  become: yes
#  with_items:
#    - virtualbox-ose
#    - virtualbox
#
#- name: Install virtualization dependencies
#  package: name={{ item }} state=present
#  become: yes
#  with_items:
#    - qemu
#    - net-tools
#    - ebtables
#    - dnsmasq
#    - bridge-utils
#    - rsync

- name: Install libvirt client tools
  package: name={{ item }} state=present
  become: yes
  with_items:
    - virt-manager
    - virt-viewer

- name: Start libvirtd
  service: name=libvirtd state=started enabled=yes
  become: yes

- name: Add user to libvirt group
  become: yes
  user:
    name={{ ansible_user_id }}
    groups=libvirt
    append=yes

