---

- name: Add repositories
  apt_repository: repo={{ item }}
  sudo: True
  with_items:
    - ppa:pi-rho/dev          # tmux, vim, rxvt
    - ppa:git-core/ppa        # git

- name: Install apps
  apt: name={{ item }} state=installed
  sudo: True
  with_items:
    - xdotool               # so vimtex knows if the pdf viewer is already open
    - xclip                 # cli clipboard management
    - git                   # commit everything

- include: nvim.yml
- include: latex.yml
- include: tmux.yml
- include: terminal.yml

