---

- name: Add repositories
  apt_repository: repo={{ item }}
  with_items:
    - ppa:pi-rho/dev
    - ppa:neovim-ppa/unstable

- name: Install apps
  apt: name={{ item }} state=installed
  with_items:
    - tmux
    - neovim
    - latexmk
    - xdotool
    - python3-unidecode
    - python3-pip
    - texlive-lang-german
    - rxvt-unicode-256color
    - fonts-dejavu-core

- name: Install python neovim
  pip: name=neovim

- name: Set neovim as default vim
  alternatives: name=vim path=/usr/bin/nvim

- name: Create hidden folder
  file: path='~/.plugins' state=directory
  sudo: False

- name: Clone repositories
  git: repo=https://github.com/{{ item }} dest="~/.plugins/{{ item.split('/')[1] }}"
  sudo: False
  with_items:
    - tmux-plugins/tmux-copycat
    - tmux-plugins/tmux-yank
    - jimeh/git-aware-prompt
    - VundleVim/Vundle.vim

- name: Deploy snippets
  copy: src=UltiSnips dest="~/.vim"
  sudo: False

- name: Deploy urxvt perl scripts
  copy: src=urxvt/perl/ dest=/usr/lib/urxvt/perl/

- name: Deploy dotfiles
  copy: src={{ item }} dest="~/.{{ item }}"
  sudo: False
  with_items:
    - bashrc
    - bash_aliases
    - tmux.conf
    - bash_profile
    - nvimrc
    - latexmkrc
    - Xresources
