---

- name: Add repositories
  apt_repository: repo={{ item }}
  with_items:
    - ppa:pi-rho/dev          # tmux, vim, rxvt
    - ppa:neovim-ppa/unstable # neovim

- name: Install apps
  apt: name={{ item }} state=installed
  with_items:
    - tmux                  # terminal multiplexer
    - neovim                # fork of vim
    - latexmk               # compile latex
    - xdotool               # so vimtex knows if the pdf viewer is already open
    - python3-unidecode     # for ultisnips vim plugin
    - python3-pip           # to install neovim python compatibility
    - texlive-lang-german   # add german latex packages
    - rxvt-unicode-256color # terminal umulator
    - fonts-dejavu-core     # terminal fonts
    - chktex                # latex syntax checker
    - puppet-lint           # puppet syntax checker

- name: Install python neovim
  pip: name=neovim          # so python plugins work

- name: Set neovim as default vim
  alternatives: name=vim path=/usr/bin/nvim

- name: Create plugins folder # for tmux plugins
  file: path=~/.plugins state=directory
  sudo: False

- name: Clone repositories
  git: repo=https://github.com/{{ item }} dest="~/.plugins/{{ item.split('/')[1] }}"
  sudo: False
  with_items:
    - tmux-plugins/tmux-copycat
    - tmux-plugins/tmux-yank
    - jimeh/git-aware-prompt

- name: Deploy snippets
  copy: src=UltiSnips dest="~/.vim"
  sudo: False

- name: Deploy urxvt perl scripts # clipboard support
  copy: src=urxvt/ dest=/usr/lib/urxvt/

- name: Deploy awesome config
  copy: src=awesome/ dest=~/.config/awesome/
  sudo: False

- name: Deploy dotfiles
  copy: src={{ item }} dest="~/.{{ item }}"
  sudo: False
  with_items:
    - bashrc
    - bash_aliases
    - bash_profile
    - tmux.conf
    - nvimrc
    - latexmkrc
    - Xresources        # rxvt
    - dircolors.256dark # solarized dircolors
    - xsessionrc
