required_plugins = %w( landrush )
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent = true
  config.landrush.enabled = true
  config.landrush.tld = 'dev'
  config.vm.hostname = 'vagrant.dev'
  config.vm.network "private_network", ip: "10.10.10.10"

  config.vm.synced_folder "~/git/digitalocean", "/var/www/vhosts",
  	owner: "vagrant",
  	group: "www-data"
  	  	
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
