alias ls='ls --color=auto'
alias ll='ls -alF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias py='python3.4'
alias python='python3.4'

alias ..='cd ..'
alias ...='cd ../..'

alias gits='git status'
alias gitc='git commit -m'
alias gita='git add'
alias gitp='git pull'
alias gitd='git diff'

alias gibb="sshfs lorenz.bischof@sftp.iet-gibb.ch: $HOME/gibb/ -o reconnect"
