alias ls='ls --color=auto'
alias ll='ls -alF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias py='python3.4'
alias python='python3.4'

alias ..='cd ..'
alias ...='cd ../..'

alias gits='git status'
alias gitc='git commit -m'
alias gita='git add'
alias gitp='git pull'
alias gitd='git diff'
alias vim='vim' #add --servername VIM

alias gibb="sshfs lorenz.bischof@sftp.iet-gibb.ch: $HOME/gibb/ -o reconnect"

volume() {
    if [ $1 ]; then
        pactl set-sink-volume 0 -- $1
    fi
    echo $(pactl list sinks | grep 'Volume: 0:' | awk '{print $3}')
}
