" Ensure vim isn't in vi mode
set nocompatible

set nowrap        " don't wrap lines
set tabstop=4     " a tab is four spaces
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set shiftwidth=4  " number of spaces to use for autoindenting
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set expandtab     " convert tabs to spaces
set showmatch     " set show matching parenthesis
set ignorecase    " ignore case when searching
set smarttab      " insert tabs on the start of a line according to
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type
set hidden        " allows switching modified buffers
highlight Search ctermbg=NONE ctermfg=yellow cterm=underline

set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set title                " change the terminal's title

filetype plugin indent on

" LATEX
let g:vimtex_latexmk_build_dir="build"
let g:vimtex_view_method="zathura"
autocmd BufRead,BufNewFile *.tex set filetype=tex
autocmd BufRead *.tex :VimtexCompile

" Setup some default ignores
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site|build)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
\}

set encoding=utf-8  " The encoding displayed.
set fileencoding=utf-8  " The encoding written to file.
syntax on

" Show unsaved changes
command! Diff w !diff % -

" Save file with root permissions
command! -bar Sudo exec 'w !sudo tee % > /dev/null' <bar> e! <bar> redraw! <bar> echo "Sudo has granted you your wish"
cabbrev w!! Sudo
cabbrev wq!! Sudo <bar> q

" Clear last search highlighting
map <silent> <Space> :noh<cr>

" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Enter> <Plug>(EasyAlign)

" Toggle Undotree
nnoremap <F5> :UndotreeToggle<cr>

" Copy and paste
vnoremap <C-c> "+y
inoremap <C-v> <C-r><C-o>"+p

" Load vim-plug
if empty(glob("~/.vim/autoload/plug.vim"))
    execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.github.com/junegunn/vim-plug/master/plug.vim'
endif

call plug#begin('~/.vim/plugged')

Plug 'Raimondi/delimitMate'
" Replace and add brackets and quotes
Plug 'tpope/vim-surround'
" Show git signs in gutter
Plug 'airblade/vim-gitgutter'
" Align common seperators
Plug 'junegunn/vim-easy-align'
" Make commenting easy
Plug 'tpope/vim-commentary'
" Syntax highlight ansible playbooks
Plug 'pearofducks/ansible-vim', { 'for': 'ansible' }
" Puppet syntax highlighting
Plug 'rodjek/vim-puppet', { 'for': 'puppet' }
" Latex compiler
Plug 'lervag/vimtex', { 'for': 'tex' }
" Improved javascript indentation and syntax
Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
" Snippets
Plug 'SirVer/ultisnips'
" List buffers
Plug 'jeetsukumaran/vim-buffergator'
" Fuzzy file opener
Plug 'ctrlpvim/ctrlp.vim'
" Undo tree visualizer
Plug 'mbbill/undotree'
" Enable repeating support for plugins
Plug 'tpope/vim-repeat'
" Seamless navigation between tmux panes and vim splits
Plug 'christoomey/vim-tmux-navigator'

call plug#end()
