" Ensure vim isn't in vi mode
set nocompatible

set nowrap        " don't wrap lines
set tabstop=4     " a tab is four spaces
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set shiftwidth=4  " number of spaces to use for autoindenting
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set expandtab     " convert tabs to spaces
set showmatch     " set show matching parenthesis
set ignorecase    " ignore case when searching
set smarttab      " insert tabs on the start of a line according to
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type
set hidden        " allows switching modified buffers
highlight Search ctermbg=NONE ctermfg=yellow cterm=underline

set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set title                " change the terminal's title

filetype plugin indent on

" LATEX
let g:vimtex_latexmk_build_dir="build"
let g:vimtex_view_method="zathura"
autocmd BufRead,BufNewFile *.tex set filetype=tex
autocmd BufRead *.tex :VimtexCompile

" Setup some default ignores
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site|build)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
\}

set encoding=utf-8  " The encoding displayed.
set fileencoding=utf-8  " The encoding written to file.
syntax on

" Show unsaved changes
command! Diff w !diff % -

" Save file with root permissions
command! -bar Sudo exec 'w !sudo tee % > /dev/null' <bar> e! <bar> redraw! <bar> echo "Sudo has granted you your wish"
cabbrev w!! Sudo
cabbrev wq!! Sudo <bar> q

" Clear last search highlighting
map <silent> <Space> :noh<cr>

" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Enter> <Plug>(EasyAlign)

" Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.plugins/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'Raimondi/delimitMate'
Plugin 'tpope/vim-surround'
Plugin 'airblade/vim-gitgutter'
Plugin 'junegunn/vim-easy-align'
Plugin 'mattn/emmet-vim'
Plugin 'tpope/vim-commentary'
Plugin 'chase/vim-ansible-yaml'
Plugin 'rodjek/vim-puppet'
Plugin 'lervag/vimtex'
Plugin 'SirVer/ultisnips'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'kien/ctrlp.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
