#!/bin/sh
echo "$1 $2 $3 $4" >> ~/test.mcabber.log
EVENT_TYPE=$1
EVENT_SUBTYPE=$2
JID=$3
FILE=$4

TITLE="Jabber"
TIMEOUT=10000

new_message_in () {
    notify-send -t $TIMEOUT "$TITLE" "New message from ${JID}."
}

if [ $EVENT_TYPE = "MSG" ] && [ $EVENT_SUBTYPE = "IN" ]
then
    new_message_in
fi
