autoload -Uz compinit promptinit
compinit
promptinit

HISTFILE="$HOME/.zsh_history"
SAVEHIST=5000
HISTSIZE=6000

bindkey -v
setopt noautomenu
setopt share_history             # Share history between all sessions
setopt hist_expire_dups_first    # Expire a duplicate event first when trimming history
setopt hist_ignore_dups          # Do not record an event that was just recorded again
setopt complete_in_word
setopt auto_cd

source /usr/share/git/completion/git-prompt.sh
source /usr/share/doc/pkgfile/command-not-found.zsh

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWCOLORHINTS=1
precmd () { __git_ps1 "%~" "%(!.#.$) "; print -Pn "\e]0;terminal\a" }
preexec () { print -Pn "\e]0;${1:gs/%/%%}\a" }


export SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh
export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
export EDITOR=vim
export KEYTIMEOUT=1

function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/NORMAL}/(main|viins)/INSERT}"
    RPS2=$RPS1
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select
setopt transientrprompt

alias ls='ls --color=auto'
alias ll='ls -alF'
alias sudo='sudo -sE'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ..='cd ..'
alias ...='cd ../..'

alias radio='(cvlc https://somafm.com/indiepop130.pls &)'
alias mergerequest='GITLAB_TOKEN=$(pass puzzle/gitlab_token) bundle exec rake mergerequest'
alias serve='python -m http.server'

alias g='git'
alias gs='git status'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gco='git checkout'
alias ga='git add'
alias gp='git pull'
alias gpr='git pull --rebase'
alias gf='git fetch'
alias gd='git diff'
alias gdc='git diff --cached'
alias gb='git branch'

alias t="task"
alias r="bundle exec rake"

vol() {
    if [ "$1" ]; then
        amixer set Master -Mq "$1"
    fi
    amixer get Master -M | sed -n "$ p" | awk '{print $4}' | sed "s/[^0-9]//g" | awk '{print $1"%"}'
}

autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

typeset -g -A key
key[PageUp]='^[[5~'
key[PageDown]='^[[6~'
key[Up]='^[[A'
key[Down]='^[[B'
key[^Left]='^[[1;5D'
key[^Right]='^[[1;5C'
key[Delete]='^[[3~'

bindkey "${key[Up]}" up-line-or-beginning-search
bindkey "${key[Down]}" down-line-or-beginning-search
bindkey "${key[^Left]}" backward-word
bindkey "${key[^Right]}" forward-word
bindkey "${key[Delete]}" delete-char

# allow ctrl-p, ctrl-n for navigate history (standard behaviour)
bindkey '^P' up-history
bindkey '^N' down-history

# allow ctrl-r to perform backward search in history
bindkey '^r' history-incremental-search-backward

# allow ctrl-a and ctrl-e to move to beginning/end of line
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
