---
# tasks file for openvpn

- name: Check for systemd
  command: pidof systemd
  register: systemd
  always_run: yes
  changed_when: false
  ignore_errors: yes

- name: set openvpn service name - systemd
  set_fact: openvpn_service_name=openvpn@{{openvpn_config_file}}.service
  when: systemd.rc == 0

- name: set openvpn service name - sysvinit/standard services
  set_fact: openvpn_service_name="openvpn"
  when: systemd.rc != 0

- name: install openvpn (yum)
  yum: name=openvpn state=present
  when: ansible_pkg_mgr == "yum"

- name: install openvpn (apt)
  apt: name={{ item }} state=present
  when: ansible_pkg_mgr == "apt"
  with_items:
    - openvpn
    - iptables-persistent

# RHEL has the group 'nobody', 'Debian/Ubuntu' have 'nogroup'
- name: Ensure group 'nogroup' is present
  group: name=nogroup state=present

- name: Setup server keys
  include: server_keys.yml
  tags:
    - server_keys

- name: copy openvpn config file
  template: src=server.conf.j2 dest=/etc/openvpn/{{openvpn_config_file}}.conf owner=root group=root
  notify:
    - restart openvpn

# ignoreerrors is required for CentOS/RHEL 6
# http://serverfault.com/questions/477718/sysctl-p-etc-sysctl-conf-returns-error
- name: enable ipv4 forwarding
  sysctl: name=net.ipv4.ip_forward value=1 ignoreerrors=yes

- name: Check for firewalld/iptables
  command: firewall-cmd --state
  register: firewalld
  always_run: yes
  changed_when: false  # Never report as changed
  ignore_errors: yes
  tags:
    - firewall

- name: Add port rules (iptables)
  include: iptables.yml
  when: firewalld.rc!=0
  tags:
    - firewall

- name: Add port rules (firewalld)
  include: firewalld.yml
  when: firewalld.rc==0
  tags:
    - firewall

- name: generate client configs
  include: client_keys.yml
  when: clients
  tags:
    - client_keys

- name: setup openvpn auto-start (init-style) & start
  service: name={{openvpn_service_name}} enabled=yes state=started
  when: systemd.rc != 0

# This separation is necessary because systemd doesn't allow individual unit files
# to be auto-started
# systemctl enable openvpn@openvpn_udp_15501.service doesn't work
# systemctl enable openvpn@.service does works
- name: setup openvpn auto-start (systemd)
  service: name=openvpn@.service enabled=yes
  when: systemd.rc == 0

# systemctl start openvpn@.service returns
# Failed to issue method call: Unit name openvpn@.service is not valid.
# systemctl start openvpn@openvpn_udp_15501.service works
- name: start openvpn now (systemd)
  service: name={{openvpn_service_name}} state=started
  when: systemd.rc == 0
