---

# Install
- include: get_info.yml
- include: install.yml
  when: "{{vagrant_upgrade}} == False"

# Upgrade
- include: get_info.yml
  when: "{{vagrant_upgrade}}"
- include: upgrade.yml
  when: "{{vagrant_upgrade}}"
