---

- name: import respondcms schema
  copy: src=schema.sql dest=/tmp
  notify: import respondcms schema part two

- name: import respondcms schema part two
  mysql_db: name=respondcms state=import target=/tmp/schema.sql login_user={{mysql_user}} login_password={{mysql_pass}}