---
# tasks file for openvpn

- name: install openvpn
  apt: name={{ item }} state=present
  with_items:
    - openvpn
    - iptables-persistent

- name: Ensure group 'nogroup' is present
  group: name=nogroup state=present

- name: Setup server keys
  include: server_keys.yml
  tags:
    - server_keys

- name: copy openvpn config file
  template: src=server.conf.j2 dest=/etc/openvpn/{{openvpn_config_file}}.conf owner=root group=root
  notify:
    - restart openvpn

- name: enable ipv4 forwarding
  sysctl: name=net.ipv4.ip_forward value=1

- name: Add port rules
  include: iptables.yml
  tags:
    - firewall

- name: Get public ip
  shell: wget -qO- http://ipecho.net/plain
  register: external_ip
  changed_when: False

- name: generate client configs
  include: client_keys.yml
  when: clients
  tags:
    - client_keys

- name: setup openvpn auto-start & start
  service: name=openvpn enabled=yes state=started